console.log("console project");
var first_name = "Rayhan";
var last_name = " Harshad";
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 30;
var b = 15;
var add = a + b ;
console.log(add);
var sub = a - b ;
console.log(sub);
var multiple = a * b ;
console.log(multiple);
var divide = a / b ;
console.log(divide);
